name: Quality checks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Check requirements lock
      run: |
          make -B requirements.txt
          git diff --exit-code requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format check
      run: |
        make format-check

    - name: Lint check
      run: |
        make lint

    - name: Type check
      run: |
        make type-check

    - name: Test
      run: |
        make test
